#!/bin/bash

echo "🚀 Intelligent Case Routing API - Railway Deployment Guide"
echo "=========================================================="
echo ""
echo "Your project is ready for deployment! Follow these steps:"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Initialize the project:"
echo "   railway init"
echo ""
echo "3. Deploy the project:"
echo "   railway up"
echo ""
echo "4. Get your production URL:"
echo "   railway domain"
echo ""
echo "📁 Project files created:"
echo "   ✅ main.py - FastAPI application"
echo "   ✅ requirements.txt - Python dependencies"
echo "   ✅ Dockerfile - Container configuration"
echo "   ✅ railway.json - Railway deployment config"
echo "   ✅ README.md - Documentation"
echo ""
echo "🔧 API Features:"
echo "   • POST /analyze-case - Classify and route cases"
echo "   • GET /health - Health check endpoint"
echo "   • GET /docs - Interactive API documentation"
echo "   • GET /model-info - Model information"
echo ""
echo "💡 After deployment, your API will be available at:"
echo "   https://your-project-name-production-xxxxx.up.railway.app"
echo ""
echo "🧪 Test your API with:"
echo "   curl -X POST 'https://your-url/analyze-case' \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"subject\":\"Payroll issue\",\"description\":\"Tax withholding problem\"}'"
echo ""
